import type { NextPage } from 'next'
import Head from 'next/head'
// Contexts
import ModalProvider from '../components/Contexts/ModalContexts'
import SelectedProvider from '../components/Contexts/SelectedContext'
// Components
import ChooseTemplate from '../components/ChooseTemplate'
import EditTemplate from '../components/EditTemplate'
import Hero from '../components/Hero'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <ModalProvider>
      <SelectedProvider>
        <div className="flex flex-col font-inter w-full cursor-default">
          <Head>
            <title>Popup Generator | Emre</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Hero/>
          <ChooseTemplate />
          <EditTemplate />
          <Footer />
        </div>
      </SelectedProvider>
    </ModalProvider>
  )
}

export default Home
