import type { NextPage } from 'next'
import Head from 'next/head'
import { AiOutlineDown } from 'react-icons/ai'
// Contexts
import ModalProvider from '../components/Contexts/ModalContexts'
import SelectedProvider from '../components/Contexts/SelectedContext'
// Components
import ChooseTemplate from '../components/ChooseTemplate'
import EditTemplate from '../components/EditTemplate'

const Home: NextPage = () => {
  return (
    <ModalProvider>
      <SelectedProvider>
        <div className="flex flex-col font-inter w-full bg-slate-100 cursor-default">
          <Head>
            <title>My First Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div id='landing' className="h-screen w-full bg-pink-300 rounded-3xl flex flex-col gap-3 justify-center items-center text-5xl">
            <a href='#templates'>Start with selecting a modal </a>
            <a href='#templates'><AiOutlineDown className="absolute bottom-0 animate-bounce" /></a> 
          </div>
          <ChooseTemplate />
          <EditTemplate />
        </div>
      </SelectedProvider>
    </ModalProvider>
  )
}

export default Home
